# Generated by nup -- do not edit by hand.
#
# This overlay applies the per-package nixpkgs pins recorded in nup.lock.json.
# Every pinned revision is imported exactly once, even when several packages
# share it, and every fetch carries its hash, so this evaluates in pure mode.
#
# Add it to your configuration once, for example:
#
#   nixpkgs.overlays = [ (import ./nup-overlay.nix) ];
#
# Regenerate with `nup init --force` after upgrading nup.

final: prev:

let
  lockPath = ./nup.lock.json;

  lock =
    if builtins.pathExists lockPath then
      builtins.fromJSON (builtins.readFile lockPath)
    else
      { packages = { }; };

  packages = lock.packages or { };
  names = builtins.attrNames packages;

  # Key the sources by revision so each tarball is fetched and imported once.
  sources = builtins.listToAttrs (
    map (
      name:
      let
        p = packages.${name};
      in
      {
        name = p.rev;
        value = { inherit (p) rev sha256; };
      }
    ) names
  );

  # Only user-facing nixpkgs config options are carried over. `prev.config` is
  # the *evaluated* config and contains module outputs plus nulls that a fresh
  # `import nixpkgs { config = ...; }` would choke on, so it cannot be reused
  # verbatim. Add your own keys here if a pinned package needs them.
  inheritedConfigKeys = [
    "allowAliases"
    "allowBroken"
    "allowInsecurePredicate"
    "allowUnfree"
    "allowUnfreePredicate"
    "allowUnsupportedSystem"
    "android_sdk"
    "checkMeta"
    "cudaCapabilities"
    "cudaForwardCompat"
    "cudaSupport"
    "joypixels"
    "permittedInsecurePackages"
    "rocmSupport"
    "segger-jlink"
  ];

  inheritedConfig = builtins.listToAttrs (
    builtins.concatMap (
      key:
      if prev.config ? ${key} && prev.config.${key} != null then
        [
          {
            name = key;
            value = prev.config.${key};
          }
        ]
      else
        [ ]
    ) inheritedConfigKeys
  );

  importSource =
    src:
    import
      (builtins.fetchTarball {
        url = "https://github.com/NixOS/nixpkgs/archive/${src.rev}.tar.gz";
        sha256 = src.sha256;
      })
      {
        # Inherit platform and the relevant config so pinned packages behave
        # like the rest of the system.
        system = prev.stdenv.hostPlatform.system;
        config = inheritedConfig;
      };

  # Lazy: an entry is only evaluated when a package from it is actually used.
  pinnedPkgs = builtins.mapAttrs (_rev: importSource) sources;

  splitPath = path: builtins.filter builtins.isString (builtins.split "\\." path);

  getAttrPath = builtins.foldl' (set: attr: set.${attr});

  # Merge `value` into `acc` at `path`. Levels that no pin touches are taken
  # from `base` (the unpinned set), so several pins can share a parent.
  setIn =
    base: acc: path: value:
    let
      head = builtins.head path;
      tail = builtins.tail path;
    in
    if tail == [ ] then
      acc // { ${head} = value; }
    else
      acc
      // {
        ${head} = setIn base.${head} (acc.${head} or base.${head}) tail value;
      };

  overlay = builtins.foldl' (
    acc: name:
    let
      p = packages.${name};
      path = splitPath p.attr;
    in
    setIn prev acc path (getAttrPath pinnedPkgs.${p.rev} path)
  ) { } names;
in
overlay
